version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src"
    update_schedule: "daily"
    automerged_updates:
      # Automerge security patches
      - match:
          dependency_type: "production"
          update_type: "security:patch"
      # Automerge Catel
      - match:
          dependency_name: "Catel.*"
          update_type: "semver:minor"
      # Automerge Orc.*
      - match:
          dependency_name: "Orc.*"
          update_type: "semver:minor"
      # Automerge Orchestra
      - match:
          dependency_name: "Orchestra.*"
          update_type: "semver:minor"